### PR TITLE
Add Massive Decks.

### PR DESCRIPTION
**Pull request by Lattyware**

### CODE REVIEW

**Comment by lukewestby** [comment]
Thanks for joining in!

**Comment by lukewestby** [comment]
@Lattyware can i change the `primaryUrl` value to be http://massivedecks.herokuapp.com/ instead of the github repo?

**Comment by Lattyware** [comment]
You can, I avoided it as I'm not sure about how permanent that URL is going to be, but if it changes I guess I can just come back and change it, so go ahead.

**Comment by lukewestby** [comment]
Sounds good, if you do change it just open up a PR or throw another comment on this one and I'll update it for you. Thanks!

**Pull request merged**
